### PR TITLE
Add Ken to WAI staff lists

### PR DESCRIPTION
**Pull request by kfranqueiro**
It looks like we list our staff members in 3 places, so I updated all of them.

Feel free to suggest wording tweaks.

(It'd be nice if it were in one place or used an include to at least avoid repetition in the repo, but that's probably something to tackle later.)

### CODE REVIEW

**Comment by shawna-slh** [comment]
Thanks for getting this started!

hummm. "website infrastructure" seems too broad. some would think that includes hardware, software, network and server components

Also would be good to explicitly call out WCAG 2 and WCAG 3.

Also would be nice to start with "supports" or such for consistency.

What about more like:
> * [Ken Franqueiro](https://www.w3.org/staff/#kfranqueiro) develops the new technical architecture for WCAG 2, WCAG 3, and the WAI website.

**Comment by kfranqueiro** [comment]
> Thanks for getting this started!
> 
> hummm. "website infrastructure" seems too broad. some would think that includes hardware, software, network and server components
> 
> Also would be good to explicitly call out WCAG 2 and WCAG 3.
> 
> Also would be nice to start with "supports" or such for consistency.
> 
> What about something more like:
> 
> > * [Ken Franqueiro](https://www.w3.org/staff/#kfranqueiro) develops the new technical architecture for WCAG 2, WCAG 3, and the WAI website.

Good points. Similar to your point RE "infrastructure" ambiguity, I wonder if there's a good way to word this that makes it clear we're referring to the websites in all 3 cases? Otherwise "technical architecture for WCAG 2, WCAG 3" might also sound overly broad? Maybe "technical architecture for WCAG and WAI websites"?

**Comment by shawna-slh** [comment]
If no objection, I'll go with for now:
> [Ken Franqueiro](https://www.w3.org/staff/#kfranqueiro) develops the new technical architecture for WCAG 2, WCAG 3, and the WAI website.

**Comment by kfranqueiro** [comment]
This was resolved by Shawn in #274 + 87c91d1 + c424bba since she was already working on site updates.

**Pull request closed without merging**
