### PR TITLE
Update symposium2.md

### PR DESCRIPTION
**Pull request by leticiaseixas**

### CODE REVIEW

**Comment by shawna-slh** [comment]
Hi @SteveALee -- is this deploy failed related to the issue from last week?

**Comment by SteveALee** [comment]
almost certainly.

@leticiaseixas in your repo please checkout the target `Gemfile.lock` . I think that should fix it. The one in the target branch looks good.

**Comment by leticiaseixas** [comment]
Hi @SteveALee, the file looks the same. Actually, for this repo, I made the changes on just one file, directly on GH web interface.

**Comment by SteveALee** [comment]
Hmm, maybe a netlify caching issue then. The error is dependency.

 Can you trigger the deploy with clean cache? Or is that team only?

**Comment by leticiaseixas** [comment]
Probably team only. 
I also noticed that I don’t have write access to this repo, so submitting a change wrote it to a new branch in my fork, so I could send a pull request. Not sure if influences something.

**Comment by SteveALee** [comment]
Thats right so I wondered if your repo had an old gem file.lockcausing the problem

**Comment by leticiaseixas** [comment]
Just updated with recent changes on master branch and the deploy worked.

**Comment by leticiaseixas** [comment]
I will close this PR now and create an updated one, modifying just the one file that I really need to update.

**Comment by SteveALee** [comment]
fingers crossed!

If it fails I'll take a look.

**Pull request closed without merging**
