### PR TITLE
Add ARIA Authoring Practices, remove DPub ARIA TF

### PR DESCRIPTION
**Pull request by jnurthen**

### CODE REVIEW

**Comment by shawna-slh** [comment]
Hi @cooper or @iherman  Would you confirm that this:
> Digital Publishing ARIA Task Force under the ARIA Working Group and the Digital Publishing Interest Group
> Comparing existing vocabularies, including IDPF’s EPUB Structural Semantic Vocabulary and ARIA Roles, to create a recommended list of digital publishing terms allowing for clear interaction with assistive technologies, easy reusability, and native validation.

should indeed be deleted from https://www.w3.org/WAI/about/groups/taskforces/

Thanks!

**Review by iherman — COMMENTED** [review]
Formally: the DPUB IG has been closed for years, ie, this TF, as described, is indeed moot. That being said, work on DPUB ARIA is still ongoing, but I'm not sure under which formal framework.

cc @tzviyasiegman @mattgarrish

**Comment by mattgarrish** [comment]
The description is really dated, since we've already published v. 1.0 of the DPUB-ARIA module and are working on 1.1 now. We're not comparing structural semantics or creating lists, but that was the TF that developed the module.

The TF page is also dated, as we're just running the maintenance work through github now.

So I don't know if the TF formally still exists, or if we're just something like an activity of the WG now, but if it does that page certainly needs some updating.

**Comment by shawna-slh** [comment]
Thank you. I will delete it.

> This page lists some active Task Forces

**Pull request merged**
