### PR TITLE
[tea] clarification on Links

### PR DESCRIPTION
**Pull request by slhenry**
@yatil - this is tea since we need to get some changed. thanks.

### CODE REVIEW

**Comment by yatil** [comment]
@slhenry Just registering my disappointment that we encourage hosted “social media” services instead of personal websites.

I’ll publish it now.

**Comment by slhenry** [comment]
Actually, **personal websites are *preferred* -- to the "about" page** or such (_rather than home page_).

How can we make that clearer?

Change:
> Link to information about the translator as an individual, such as about or biography page or acceptable social media page.

maybe ->
> Link to information about the translator as an individual, such as about or biography page on personal website or acceptable social media page.

or better yet ->
> Link to information about the translator as an individual, such as about or biography page on personal website or organization website.

And Change

> Cannot include:
> Links to organizations. Links to personal home pages.

to ->

> Cannot include:
> Links to organizations. Links to home pages rather than about pages.

**Comment by yatil** [comment]
Okay, I misunderstood. Hard to make and enforce that distinction, I’d argue that my home page is also my “about page”: https://yatil.net

Most important is that we don’t outrage personal pages.

**Comment by slhenry** [comment]
> Most important is that we don’t <del>outrage</del> [!sic thanks autocorrect!] outlaw personal pages.

I was wondering about that! ;-)

**Pull request merged**
