### PR TITLE
Create symposium2.md

### PR DESCRIPTION
**Pull request by shawna-slh**
Preview: https://deploy-preview-166--wai-about-wai.netlify.app/about/projects/wai-coop/symposium2/

### CODE REVIEW

**Comment by shawna-slh** [comment]
hi @leticiaseixas a couple of things I noticed:

Should we now delete "[Draft]" from the title in the frontmatter?

In skimming, my mind saw:
> 1-10 January 2023 and 2-11 January 2023

Perhaps it would be better to use different punctuation? Maybe:
> Day 1: 10 January 2023

or perhaps add the day of the week and use an m-dash?
> Day 1 &mdash; Tuesday 10 January 2023

or if you add the day, then regular dash as you have it is probably OK:
> Day 1 - Tuesday 10 January 2023

Personally, I mildly prefer
> Day 1: Tuesday 10 January 2023

and I'm fine with whatever you all go with - even leaving it as if if there is a reason to..

**Comment by leticiaseixas** [comment]
Hi @shawna-slh:

- Yes, we should remove Draft.

- I like your suggestion: 
> Day 1: Tuesday 10 January 2023

- We should also probably include the link on the WAI-CooP main page

For some reason I'm not able to edit this PR anymore. Feel free to edit the page, otherwise I think I need to open another PR for this.

**Comment by shawna-slh** [comment]
Hi @carlosapaduarte and @leticiaseixas , another question: For the [previous symposium](https://www.w3.org/WAI/about/projects/wai-coop/symposium1/), the navigation is:
> WAI-CooP / Online Research Symposium

This shows up in the breadcrumb and the left nav.

What are your thoughts on what we want to use for this one, and probably change previous? Simplest would be:
> WAI-CooP / Online Research Symposium 1
> WAI-CooP / Online Research Symposium 2

though that's kinda boring :-)
maybe:
> WAI-CooP / Research Symposium: Shape the Future  _(though that will wrap a lot in the nav)_
> WAI-CooP / Research Symposium: AI

maybe:
> WAI-CooP / Research Symposium: 2021
> WAI-CooP / Research Symposium: AI

**Comment by shawna-slh** [comment]
> For some reason I'm not able to edit this PR anymore. Feel free to edit the page, otherwise I think I need to open another PR for this.

I'm happy to. easy enough.

**Comment by carlosapaduarte** [comment]
> What are your thoughts on what we want to use for this one, and probably change previous? Simplest would be:

This is my favourite suggestion.
 
> > WAI-CooP / Research Symposium: 2021
> > WAI-CooP / Research Symposium: AI

**Pull request merged**
